language: c

git:
  submodules: false

script:
- |
  set -e
  echo "$TRAVIS_EVENT_TYPE"
  test "$TRAVIS_EVENT_TYPE" = push || exit 0
  test -n "$COPR_PUSH_WEBHOOK"
  curl -o copr-build https://raw.githubusercontent.com/praiskup/copr-ci-tooling/master/copr-travis-submit
  exec bash copr-build

