#! /bin/bash

build_deps='
    autoconf
    automake
    bison
    gcc
    gettext-devel
    git
    make
    rsync
    texinfo
    wget
'

copr edit-package-custom \
    --script-chroot fedora-latest-x86_64 \
    --script-builddeps "$(echo $build_deps)" \
    --name tar \
    praiskup/tar-ci \
    --script copr-custom-script
