---
name: RPM build in Fedora Copr
on:
  push:
    branches: [ci]
  pull_request:
    branches: [ci]

jobs:
  build:
    name: Submit a Copr build
    runs-on: ubuntu-latest

    steps:
      - name: Check out proper version of sources
        uses: actions/checkout@v1

      - name: Submit the build
        env:
          COPR_PR_WEBHOOK: https://copr.fedorainfracloud.org/webhooks/custom/19594/a2aba6c0-7792-4007-8886-2cc0f411801e/tar/
          COPR_PUSH_WEBHOOK: ${{ secrets.COPR_PUSH_WEBHOOK }}
        run: |
          curl https://raw.githubusercontent.com/praiskup/copr-ci-tooling/main/copr-gh-actions-submit > submit
          bash submit ${{ github.event.pull_request.number }}
